version: '3'

tasks:
  sync:
    desc: Sync the Taskfile.yaml to ~
    cmds:
      - curl https://raw.githubusercontent.com/dodizzle/goUtilities/refs/heads/main/Taskfile.yaml -o ~/Taskfile.yaml

  G:
    desc: Go to golang home
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - 