version: '3'

tasks:
  docker-build:
    desc: docker build
    cmds:
    - docker build -t webservice:latest .

  docker-up:
    desc: docker compose up
    cmds:
    - docker-compose up -d
    - docker container logs -f webservice

  docker-down: 
    desc: docker compose down
    cmds:
    - docker-compose down --remove-orphans
    - rm -rf pgdata
    - docker system prune -f